import { useState, useEffect } from 'react';
import {
  captureDisclaimerShown,
  captureDisclaimerCheckboxToggled,
  captureDisclaimerAccepted,
} from '../lib/analytics';

interface Props {
  onAccept: () => void;
}

export function WarningModal({ onAccept }: Props) {
  const [checked, setChecked] = useState(false);

  useEffect(() => { captureDisclaimerShown(); }, []);

  return (
    <div className="fixed inset-0 z-50 flex items-start sm:items-center justify-center overflow-y-auto bg-black/90 backdrop-blur-sm py-4 sm:py-0">
      <div className="mx-4 w-full max-w-lg sm:max-w-[717px] rounded-xl border border-yellow-500/60 bg-gray-950 p-8 shadow-[0_0_60px_rgba(251,191,36,0.15)]">
        {/* Header */}
        <div className="mb-6 text-center">
          <div className="mb-3 inline-block rounded-lg bg-yellow-500/10 px-4 py-2 text-sm font-bold uppercase tracking-widest text-yellow-400 border border-yellow-500/30">
            Important Disclaimer
          </div>
          <h1 className="text-2xl font-bold text-white font-mono">
            WFA
          </h1>
          <p className="mt-1 text-sm text-gray-400 font-mono">Wallace Financial Advisor</p>
        </div>

        {/* Warning content */}
        <div className="mb-6 space-y-3 rounded-lg border border-red-900/50 bg-red-950/30 p-5 text-sm text-gray-300 leading-relaxed">
          <p className="font-semibold text-red-400 text-base">
            DO NOT buy or sell anything based on this app.
          </p>
          <p>
            This application scrapes Reddit's r/wallstreetbets and uses AI to generate
            stock commentary. It is entertainment only and provides no financial advice
            whatsoever.
          </p>
          <p>
            The recommendations shown here are generated by AI agents analyzing meme
            stock hype. They are not based on sound financial analysis, professional
            research, or any form of qualified advice.
          </p>
          <p className="text-yellow-400/80">
            Acting on anything this app says could result in significant financial loss.
            Past meme stock performance does not indicate future results — mostly because
            there is no future for most of these stocks.
          </p>
          <p className="text-gray-500 text-xs">
            Not a registered investment advisor. Not a financial advisor. Not a broker.
            Not even a particularly responsible adult.
          </p>
        </div>

        {/* Checkbox */}
        <label className="mb-6 flex cursor-pointer items-start gap-3 text-sm text-gray-300">
          <input
            type="checkbox"
            checked={checked}
            onChange={(e) => { setChecked(e.target.checked); captureDisclaimerCheckboxToggled(e.target.checked); }}
            className="mt-0.5 h-4 w-4 shrink-0 cursor-pointer accent-yellow-500"
          />
          <span>
            I understand this is for entertainment purposes only, and I will not make
            any financial decisions based on this app.
          </span>
        </label>

        {/* Button */}
        <button
          onClick={() => { captureDisclaimerAccepted(); onAccept(); }}
          disabled={!checked}
          className={`w-full rounded-lg py-3 text-sm font-bold font-mono uppercase tracking-wider transition-all duration-200 ${
            checked
              ? 'bg-yellow-500 text-black hover:bg-yellow-400 active:scale-95'
              : 'cursor-not-allowed bg-gray-800 text-gray-600'
          }`}
        >
          {checked ? 'I Accept — Show Me the Madness' : 'Check the box first'}
        </button>

        <p className="mt-5 text-center text-xs text-gray-700 font-mono">
          A personal experiment by Sebastien Medan · Not a financial product.
        </p>
      </div>
    </div>
  );
}
